import type { Ordbok } from "./felles";

/**
 * English. The Norwegian statutes keep their Norwegian names, with a short
 * gloss the first time they appear: «anskaffelsesforskriften § 24-9» is the
 * name of a Norwegian regulation, not a phrase. Translate it and the reader
 * can no longer look it up — which is the whole point of citing it.
 */
export const en: Ordbok = {
  sprak: { velg: "Language", norsk: "Norwegian", svensk: "Swedish", engelsk: "English" },

  meny: {
    oversikt: "Overview",
    nyKontroll: "New check",
    bulk: "Bulk check",
    kjede: "Supply chain",
    tilbud: "Abnormally low tenders",
    anskaffelser: "Procurements",
    leverandorer: "Suppliers",
    jav: "Conflicts of interest",
    espd: "ESPD",
    support: "Support",
    konto: "Account",
  },

  ansattmeny: {
    konton: "Accounts",
    attgora: "To do",
    support: "Support",
    kontakt: "Contact",
    leads: "Leads",
    offerter: "Quotes",
    fakturering: "Invoicing",
    onboarding: "Onboarding",
    kreditt: "Credit checks",
    kallor: "Source health",
    marginal: "Margin",
    logg: "Access log",
    team: "Team and access",
  },

  skall: {
    kontoenDin: "Your account",
    loggUt: "Sign out",
    loggerUt: "Signing out …",
    relavoInternt: "Relavo internal →",
    tilbakeTilKunde: "← Back to the customer view",
    internt: "Internal",
    apneMenyen: "Open the menu",
    lukkMenyen: "Close the menu",
    personal: "Staff",
    superadmin: "Superadmin",
  },

  felles: {
    lagre: "Save",
    lagrer: "Saving …",
    avbryt: "Cancel",
    tilbake: "Back",
    neste: "Next",
    hoppOver: "Skip",
    sok: "Search",
    vis: "Show",
    skjul: "Hide",
    apne: "Open",
    sender: "Sending …",
    henter: "Loading …",
    valgfritt: "optional",
    ingenting: "Nothing here yet.",
    status: "Status",
    endreStatus: "Click to change status",
  },

  sider: {
    oversikt: {
      tittel: "Overview",
      tekst: "Where you stand on the duty to verify, and what needs you today.",
    },
    nyKontroll: {
      tittel: "New check",
      tekst:
        "Six steps, three of them optional. The result is stored unchanged as evidence that the duty to verify under anskaffelsesloven § 5i has been met.",
    },
    bulk: {
      tittel: "Bulk check",
      tekst:
        "Paste the organisation numbers for the whole portfolio and check them all in one go.",
    },
    kjede: {
      tittel: "Supply chain",
      tekst:
        "§ 5k allows at most two tiers of subcontractors in construction, civil engineering and cleaning. Breaches are flagged — and the two lawful ways out are to cut the tier or seek an exemption from the contracting authority.",
    },
    tilbud: {
      tittel: "Abnormally low tenders",
      tekst:
        "The deviation is measured against the median of the other tenders. Where a tender is abnormally low, § 24-9 requires you to ask the tenderer to explain it in writing before you may reject it.",
    },
    anskaffelser: {
      tittel: "Procurements",
      tekst:
        "The contracts the checks belong to. The case number here is the one you enter in the procurement record.",
    },
    leverandorer: {
      tittel: "Suppliers",
      tekst: "Every supplier you have checked, with the latest known status.",
    },
    jav: {
      tittel: "Conflicts of interest",
      tekst:
        "Board members at the supplier are cross-checked against the people taking part in the procurement. A match is a warning of possible disqualification under forvaltningsloven § 6, not a conclusion.",
    },
    espd: {
      tittel: "ESPD and self-declarations",
      tekst:
        "The self-declaration covers the part of the qualification assessment the registers cannot answer. Where one is missing it can be requested afterwards under § 23-5 — and the deadline is tracked here.",
    },
    support: {
      tittel: "Support",
      tekst:
        "Raise a ticket and follow the reply here. Choose notifications and you get an email when the ticket is answered or changes status.",
    },
    konto: {
      tittel: "Account settings",
      tekst:
        "Your own details, the organisation you belong to, and who has access.",
    },
  },

  ansattsider: {
    konton: {
      tittel: "Accounts",
      tekst: "Every customer account, the plan they are on and how much of the quota they have used.",
    },
    attgora: {
      tittel: "To do",
      tekst:
        "What needs a person today, drawn from invoices, quotes, leads and source health. Red is urgent.",
    },
    support: {
      tittel: "Support",
      tekst:
        "Tickets from every account. Reply here and it goes straight to the customer, and the ticket moves to Waiting on the customer.",
    },
    kontakt: {
      tittel: "Contact",
      tekst:
        "Messages from the contact form on the landing page. Mark as handled once someone has replied.",
    },
    leads: {
      tittel: "Leads",
      tekst:
        "People who are interested but not yet customers. The next-step column is what decides whether something falls through the cracks.",
    },
    offerter: {
      tittel: "Quotes",
      tekst:
        "Quotes sent, what they are worth and when they expire. Search for the customer's name and the organisation number and contact details fill themselves in.",
    },
    fakturering: {
      tittel: "Invoicing",
      tekst:
        "Invoices per account, with due date and status. The invoice number is assigned automatically, running per year.",
    },
    onboarding: {
      tittel: "Onboarding",
      tekst:
        "Where each customer stands in getting started. An account counts as live once it has run its first check, not when the contract is signed.",
    },
    kreditt: {
      tittel: "Credit checks",
      tekst:
        "Checks on customers and prospective customers before we invoice. Every run is stored unchanged with a timestamp, so it can be retrieved later.",
    },
    kallor: {
      tittel: "Source health",
      tekst:
        "Response times, error rates and cost per register. If a source is down, the customer's report should say so rather than keep quiet about it.",
    },
    marginal: {
      tittel: "Margin",
      tekst:
        "What each account brings in against what the register lookups cost us. Accounts running at a loss are shown in red.",
    },
    logg: {
      tittel: "Access log",
      tekst:
        "Who on our side has opened which customer's data, and why. The log should be showable to the customer without us having to tidy it first.",
    },
    team: {
      tittel: "Team and access",
      tekst:
        "Who works here and what each person may see. Access to read customer data is separate from access to change settings — one does not follow from the other.",
    },
  },

  landing: {
    nav: { meny: "Menu", plattform: "Platform", regelverk: "The rules", priser: "Pricing", sporsmal: "Questions", loggInn: "Sign in", komIGang: "Get started" },
    hero: {
      nytt: "New",
      pille: "in force from 1 July 2026 →",
      tittel: "The check you have to do. The proof you have to keep.",
      lead: "Relavo pulls company data, tax arrears and payment defaults, maps how deep the supply chain actually runs, and stores the result as evidence that the duty to verify under § 5i has been met.",
      sePriser: "See pricing",
      note: "From 590 NOK per check. No lock-in.",
    },
    kilder: { byggerPa: "Built on" },
    regelverk: {
      eyebrow: "The rules",
      tittel: "One amendment, four numbers that matter.",
      undertittel: "From 1 July 2026 the duty to verify is explicit.",
      tall: [
        "tiers of subcontractors is the ceiling in construction, civil engineering and cleaning under § 5k",
        "median for a lookup against Enhetsregisteret, the Norwegian company register",
        "registers gathered into one report, with source and date on every line",
        "requires that the check can be documented afterwards, not merely carried out",
      ],
    },
    plattform: {
      eyebrow: "More features",
      raskt: "The answer arrives before you can open the next tab.",
      kjede: "The supply chain, all the way down",
      krav: "Every requirement as a line you can tick",
      laveTilbud: "Abnormally low tenders",
      overvaking: "Continuous monitoring",
      tittel: "One check, every register.",
      kjedeD: "§ 5k allows at most two tiers of subcontractors in construction, civil engineering and cleaning. Enter the chain you have and any breach is flagged at once — along with the two usual ways out.",
      kravD: "The report follows the law point by point, citing the same provisions you quote in the procurement record.",
      laveTilbudD: "The deviation is calculated against the other tenders, and you get a draft of the written explanation § 24-9 requires you to request.",
      overvakingD: "Bankruptcy, compulsory dissolution and new payment defaults are caught the day they are registered, not at the next check.",
      rapportD: "Every run is stored unchanged with source and date on each line. What has not been checked is listed as not checked.",
      rapport: "A report that holds up",
    },
    priser: {
      eyebrow: "Pricing",
      tittel: "One price, the whole report.",
      undertittel: "No per-lookup add-ons and no surprises on the invoice.",
      vanligst: "Most common",
      planer: [
        { navn: "Supplier check", enhet: "NOK", beskrivelse: "One check, full report as PDF. No subscription.", knapp: "Run one check", punkter: ["Company data and roles", "Tax, VAT and payment defaults", "Chain check against § 5k", "Report as PDF"] },
        { navn: "Standard", enhet: "NOK/month", beskrivelse: "Continuous monitoring of the suppliers in your portfolio.", knapp: "Start Standard", punkter: ["Everything in the single check", "Every source in every check", "Daily monitoring", "Bulk checks and procurements", "Assessment of low tenders"] },
        { navn: "Enterprise", enhet: "NOK/month", beskrivelse: "Several entities under one agreement, with an API.", knapp: "Start Enterprise", punkter: ["Everything in Standard", "Several entities and workspaces", "API access", "A named contact", "Data processing agreement"] },
      ],
    },
    faq: {
      eyebrow: "Questions",
      tittel: "What people ask first.",
      sporsmal: [
        { q: "Do you check whether someone has a criminal conviction?", a: "No, and no commercial provider can. Under personopplysningsloven § 11, processing data on criminal convictions is in practice reserved for public authorities, and Lovdata offers no machine access to court decisions. We check companies, not individuals. That part of the qualification assessment is covered by the supplier's ESPD self-declaration, which is stored as an attachment to the check." },
        { q: "Are there add-ons beyond the subscription?", a: "No. The price covers the finished report, however many registers it draws on. You are buying the assessment and the documentation, not individual lookups, and the invoice looks the same every month." },
        { q: "Does the report hold up as evidence under § 5i?", a: "Every run is stored unchanged with the time, source and result on each line, and can be retrieved later. Sources we got no answer from are listed as not checked rather than left out — a report that stays quiet about its gaps is worse than no report." },
        { q: "We are based in Sweden. Does it work?", a: "Relavo is built for Norwegian organisation numbers and Norwegian rules. The core of the assessment follows the same EU directive across the EEA, but the data sources and the statutes are Norwegian." },
      ],
    },
    close: {
      tittel: "How deep is the chain in your largest contract?",
      tekst: "Run one check and see. You do not need a subscription to try it.",
      snakkMedOss: "Talk to us",
    },
    foot: {
      tekst: "Relavo checks companies, not individuals. Data on criminal convictions is not processed.",
      vilkar: "Terms",
      personvern: "Privacy",
      cookies: "Cookies",
      kontakt: "Contact",
    },
  },
  ui: {
    selskap: "Company", leverandor: "Supplier", bransje: "Sector",
    risiko: "Risk", sistKontrollert: "Last checked", aldri: "Never",
    saksnummer: "Case number", anskaffelse: "Procurement",
    konkurranseform: "Procedure", avtaleverdi: "Contract value",
    periode: "Period", kontroller: "Checks",
    navn: "Name", rolle: "Role", lagtTil: "Added",
    opplysning: "Detail", verdi: "Value",
    hva: "What", nar: "When", tidspunkt: "Time", utlostAv: "Triggered by",
    resultat: "Result", demodata: "from the prototype's demo data",
  },
  risiko: { lav: "Low", middels: "Medium", hoy: "High" },
  oversikt: {
    iPortefoljen: "suppliers in the portfolio",
    kontrollerKjort: "checks run",
    medHoyRisiko: "at high risk",
    dokumentert: "documented under § 5i",
    frister: "Deadlines running.",
    espdEn: "ESPD declaration is past its deadline.",
    espdFlere: "ESPD declarations are past their deadline.",
    seDem: "See them",
    kravVenter: "requests for explanation are awaiting assessment.",
    kontrollplikt: "Duty to verify, § 5i",
    avDokumentert: "suppliers documented",
    forklaring:
      "The check must be documentable afterwards, not merely carried out. Suppliers without a stored check do not count.",
    kjorEnKontroll: "Run a check →",
    kreverNoe: "Needs you",
    sisteKjoringer: "Recent runs",
  },
  leverandorer: {
    seKoblingene: "See the connections",
    kunneIkkeHente: "Could not load suppliers:",
    ingenEnna: "No suppliers yet. Run your first check to get started.",
    styretDeltakere: "board members who are also registered as participants in the procurement.",
    muligKonfliktKort: "Possible conflict of interest",
    muligKonflikt: "Possible conflict of interest.",
    harEn: "supplier has",
    harFlere: "suppliers have",
  },
  jav: {
    eiersiden:
      "Ownership has not been checked. Aksjonærregisteret, the Norwegian shareholder register, is published by Skatteetaten as an annual file rather than a lookup service, so ownership cannot yet be cross-checked automatically.",
    utenDeltakere:
      "Without them there is nothing to cross the board against, and the check has not been carried out — not passed.",
    kunneIkkeHente: "Could not load matches:",
    funnet: "Found",
    ingenFunnet: "No possible conflicts of interest found.",
    identiskNavnMerke: "Identical name",
    tegnsAvvik: "characters apart",
    fodt: "b.",
    styre: "Board", dagligLeder: "Managing director", eier: "Owner",
    naerRelasjon: "Close relation",
    muligeKoblinger: "possible connections",
    identiskNavn: "with an identical name",
    skrivevariasjon: "with a small spelling variation",
    deltakere: "participants registered",
    ingenDeltakere: "No procurement participants are registered.",
    hosLeverandoren: "At the supplier",
    hosDere: "On your side",
    kobling: "Connection",
    sikkerhet: "Confidence",
  },
  bulk: {
    lastOpp: "Upload a list",
    velgFil: "Choose file",
    leserFilen: "Reading the file …",
    filhjelp: "Excel, CSV or text. The file is read here in your browser and is not sent anywhere.",
    numre: "numbers",
    ellerLimInn: "or paste",
    organisasjonsnumre: "Organisation numbers",
    limhjelp: "One number per line, or separated by commas. The check digit is validated with modulus 11 as you type.",
    gyldige: "valid",
    ugyldige: "invalid",
    tomLista: "Clear the list",
    kjor: "Run",
    kontroller: "checks",
    koHjelp: "Running these needs a background queue — a hundred lookups cannot be done in one request. Not connected yet.",
    nummer: "Number",
    klarForOppslag: "Ready for lookup",
    ingenTall: "Found no nine-digit numbers in the file. Are the organisation numbers split across several columns?",
    kunneIkkeLese: "Could not read the file. Is it damaged, or password-protected?",
  },
  kjede: {
    alle: "All",
    overGrensen: "Over the limit",
    bareOver: "Showing only chains with more than two tiers.",
    klikkForAFolde: "Click a chain to collapse it.",
    ledd: "tiers",
    hovedleverandor: "Main contractor",
    leddNr: "Tier",
    bruddTittel: "Breach of § 5k.",
    bruddTekst:
      "Either the bottom tier is cut, or the contracting authority must grant an exemption and record the reasons in the procurement record.",
    kjedenHar: "The chain has",
    grensenEr: "tiers; the limit is",
    innenfor: "Within the limit in § 5k",
  },
  konto: {
    sprakTittel: "Language",
    sprakTekst: "Applies to the interface. Quotes, letters and terms are always in Norwegian — they go to Norwegian recipients and must be filed as records.",
    kontoDeg: "You",
    kontoTofaktor: "Two-factor",
    engangskodeFraMobil: "one-time code from your phone",
    organisasjonen: "The organisation",
    tilgang: "Access",
    teknisk: "Technical",
    oppgiDisse: "quote these when contacting support",
    leverandorerLagret: "Suppliers stored",
    kontrollerLagret: "Checks stored",
    organisasjonsId: "Organisation ID",
    dinBrukerId: "Your user ID",
    opprettetDato: "Created",
    bareAdministrator: "Only an administrator can change these.",
    planenErFull: "The plan is full.",
    passordkrav: "At least {n} characters, with upper and lower case, a digit and a special character. It cannot contain your email address.",
    lagret: "Saved.",
    lagreNavn: "Save name",
    nyttPassord: "New password",
    gjentaPassordet: "Repeat the password",
    byttPassord: "Change password",
    navnPaOrganisasjonen: "Organisation name",
    organisasjonsnummer: "Organisation number",
    planStyres: "The plan is set by the subscription and cannot be changed here.",
    nyBruker: "New user",
    opprett: "Create",
    midlertidigPassord: "Temporary password",
    bruker: "User",
    administrator: "Administrator",
    passordHjelp:
      "The user signs in with this password and should change it themselves under Account settings.",
    deg: "— you",
    tofaktorPa: "On",
    tofaktorAv: "Not set up",
    tofaktorForklaring:
      "A one-time code from your phone in addition to the password. Optional, but recommended — the account gives access to supplier data and check history.",
    settOpp: "Set up two-factor",
    slaAv: "Turn off",
    autentiseringsapp: "Authenticator app",
    skannKoden:
      "Scan the code with Google Authenticator, 1Password, Aegis or another authenticator app.",
    fikkIkkeSkannet: "Cannot scan it? Enter the key manually",
    skrivKoden: "Enter the code your app shows",
    slattPa: "Two-factor is on.",
    slattAv: "Two-factor is off.",
    qrAlt: "QR code for two-factor",
  },
  sak: {
    nySak: "New ticket",
    hvaGjelderDet: "What is it about?",
    beskrivSaken: "Describe the issue",
    emneEksempel: "Wrong risk level on Solstrand Renhold",
    meldingEksempel: "What happened, and what did you expect instead?",
    varsleValg: "Email me when the ticket is answered or changes status.",
    sendInn: "Send",
    varsleMeg: "Notify me by email",
    sendSvar: "Send reply",
    meldinger: "messages",
  },
  veiviser: {
    steg: ["Company", "Procurement", "Case details", "Pay and HSE", "Self-declaration", "Summary"],
    orgnummer: "Organisation number",
    hintNiSiffer: "Nine digits. The check digit is validated with modulus 11 before lookup.",
    hintKlar: "Nine digits, check digit valid. Ready for lookup.",
    slaOpp: "Look up in Enhetsregisteret",
    slaarOpp: "Looking up …",
    oppslagFeilet: "The lookup failed.",
    ingenKontakt: "Could not reach Enhetsregisteret.",
    offentligJa: "Yes, public procurement",
    offentligJaTekst: "Full check against grounds for exclusion, tax certificate, the tier limit and the apprentice requirement.",
    offentligNei: "No, private purchase",
    offentligNeiTekst: "Checks company data, finances and sanctions lists. No assessment against the statutes.",
    velg: "Choose …",
    saksnummer: "Case number", bestiller: "Requesting unit", saksbehandler: "Case handler",
    konkurranseform: "Procedure", avtaleFra: "Contract from", avtaleTil: "Contract to",
    avtaleverdi: "Contract value (NOK)", opsjon: "Option", ingenOpsjon: "No option",
    tariffTittel: "Collective agreement, HSE cards and pay conditions",
    kryssAv: "Tick what you have confirmed",
    espdOffentlig: "The ESPD self-declaration covers the part of the qualification assessment we cannot check against the registers.",
    espdPrivat: "For private purchases a self-declaration is optional, but it is stored as an attachment if there is one.",
    espdLevert: "Submitted with the tender",
    espdLevertTekst: "Taken from the procurement and compared against the registers. Contradictions are flagged as grounds for exclusion under § 24-2 third paragraph.",
    espdMangler: "Not submitted — request it afterwards",
    espdManglerTekst: "A missing self-declaration is normally a defect that can be remedied under § 23-5, unlike the content of the tender itself.",
    fristEttersending: "Deadline for submission",
    tiVirkedager: "Ten working days is usual.",
    kjorKontrollen: "Run the check",
    kjorer: "Running …",
    organisasjonsform: "Legal form", ansatte: "Employees", registrert: "Registered",
    konkurs: "Bankruptcy", underTvangsavvikling: "In compulsory dissolution", underAvvikling: "In dissolution",
    ingenKonkurs: "No bankruptcy or dissolution registered",
    avvisningsgrunn: "Ground for exclusion under § 24-2:",
    typeInnkjop: "Type of purchase",
    offentligAnskaffelse: "Public procurement", privatInnkjop: "Private purchase",
    feltUtfylt: "fields filled in", hoppetOver: "Skipped",
    bekreftet: "confirmed", ingenBekreftet: "None confirmed",
    av: "of",
  },
  internt: {
    ansatte: "staff",
    superadminAntal: "superadmins",
    personalAntal: "staff without superadmin",
    kundanvandare: "customer users",
    obetald: "Unpaid",
    betald: "Paid",
    forfallenStatus: "Overdue",
    kreditnota: "Credit note",
    utestaende: "outstanding",
    forfalne: "overdue",
    betalt: "paid",
    fakturor: "invoices",
    ny: "New",
    kontaktad: "Contacted",
    demo: "Demo",
    offertStatus: "Quote",
    vunnen: "Won",
    forlorad: "Lost",
    vunna: "won",
    apneSmall: "open",
    valj: "Choose …",
    organisasjonsnummer: "Organisation number",
    superadminRolle: "Superadmin",
    personalRolle: "Staff",
    administrator: "Administrator",
    anvandare: "User",
    aktivaLarm: "Active alerts",
    statusKol: "Status",
    kontaktKol: "Contact",
    leverantorerKol: "Suppliers",
    skickaTill: "Send to",
    skrivUt: "Print / save as PDF",
    kunneIkkeKopiere: "Could not copy. Select the link below.",
    sendIgjen: "Send again",
    sendTilbudet: "Send the quote",
    kopiert: "Copied ✓",
    kopierLenke: "Copy link",
    kundenFarLenke: "The customer gets a link, not an attachment. Then they can answer where they read it — and we can see that it was read, what they answered and why.",
    undersokelsesplikt: "Duty to investigate",
    normalt: "Normal",
    tilbyder: "Tenderer",
    tilbudssum: "Tender sum",
    avvikMotMedian: "Deviation from median",
    ingenSakerKunde: "No tickets yet. Raise one with the button above.",
    venterPaDeg: "waiting on you",
    tilForsiden: "Relavo, to the front page",
    aktiveKontoer: "active accounts",
    manedsinntekt: "monthly revenue",
    underKontroll: "suppliers under check",
    underOvervaking: "under continuous monitoring",
    konto: "Account",
    enhet: "Unit",
    plan: "Plan",
    forbruk: "Usage",
    avtaleTom: "Contract until",
    sist: "Last",
    demodataStaff: "demo data from relavo-staff.html",
    haster: "Urgent",
    kanVente: "Can wait",
    apne: "Open →",
    detalj: "Detail",
    vad: "What",
    var: "Where",
    ingentingBrenner: "Nothing is on fire right now.",
    forfallenFaktura: "Overdue invoice",
    ubetaltFaktura: "Unpaid invoice",
    tilbudUtgatt: "Sent, but the validity period has passed",
    nesteStegPassert: "The next step is overdue",
    folgOpp: "Follow up",
    tilbudTil: "Quote to",
    harGattUt: "has expired",
    gikkUt: "expired",
    skulleFolgtsOpp: "should have been followed up",
    alarm: "Alert",
    aktivtSiden: "active since",
    forfaller: "due",
    nyNotis: "new notification",
    nyeNotiser: "new notifications",
    merkAlleLest: "Mark all as read",
    merkLest: "Mark as read",
    sakerTotalt: "tickets in total",
    apneSaker: "open",
    venterPaOss: "waiting on us",
    venterPaKunden: "waiting on the customer",
    ingenSaker: "No tickets yet.",
    meldingerTotalt: "messages in total",
    vilSeDemo: "want a demo",
    sporOmPris: "asking about price",
    ubehandlet: "unhandled",
    avsender: "Sender",
    gjelder: "About",
    melding: "Message",
    inn: "Received",
    ingenMeldinger: "No messages yet.",
    leadsTotalt: "leads in total",
    vinnerandel: "win rate of decided leads",
    nyttLead: "New lead",
    bolag: "Company",
    kontaktperson: "Contact",
    kilde: "Source",
    landingsside: "Landing page",
    messe: "Trade fair",
    anbefaling: "Referral",
    utgaendeKontakt: "Outbound",
    nesteSteg: "Next step",
    notis: "Note",
    opprettet: "Created",
    ingenLeads: "No leads yet. Create the first with the button above.",
    visLenke: "View →",
    venterPaSvar: "awaiting a reply",
    samletVerdi: "total contract value",
    sendtUtenSvar: "sent without a reply",
    opplegg: "Package",
    lopetid: "Term",
    verdi: "Value",
    gyldigTom: "Valid until",
    ingenTilbud: "No quotes yet.",
    apnetAvKunden: "Opened by the customer",
    ikkeApnet: "Not opened yet",
    nyOfferte: "New quote",
    koblTilLead: "Link to a lead",
    ingenKobling: "No link",
    frittTilbud: "Custom offer",
    frittTilbudTekst: "An agreed number of checks at an agreed price, outside the plans.",
    antallKontroller: "Number of checks",
    totalpris: "Total price in NOK",
    notatHjelp: "What is included, and why the price differs from the plan.",
    lopetidAr: "Term in years",
    rabatt: "Discount in per cent",
    gyldigTil: "Valid until",
    lagreTilbud: "Save the quote",
    nyFaktura: "New invoice",
    fakturaadresse: "Invoice address",
    deresReferanse: "Your reference",
    koblTilKonto: "Link to an account",
    ingenKonto: "No account",
    belopIKr: "Amount in NOK",
    forfallsdato: "Due",
    fakturanr: "Invoice no.",
    belop: "Amount",
    ingenFakturaer: "No invoices yet.",
    kontrollerKjort: "checks run",
    medHoyRisiko: "at high risk",
    medMiddels: "at medium risk",
    registrePakoblet: "registers connected",
    lavRisiko: "Low risk",
    middelsRisiko: "Medium risk",
    hoyRisiko: "High risk",
    advarsel: "Warning",
    alvorlig: "Serious",
    ikkeKontrollert: "Not checked",
    ingenKredittsjekk: "No checks run yet. Enter an organisation number above.",
    kjorKredittkontroll: "Run a credit check",
    kjorKontroll: "Run check",
    kontrollerer: "Checking …",
    niSiffer: "Nine digits. The check digit is validated with modulus 11.",
    klarForKontroll: "Ready to check.",
    anropDenneManeden: "calls this month",
    medianSvartid: "median response time",
    aktiveAlarmer: "active alerts",
    kildeKol: "Source",
    regel: "Rule",
    siden: "Since",
    tiltak: "Action",
    kilder: "Sources",
    hvaDenGir: "What it provides",
    anrop: "Calls",
    svartid: "Response time",
    kostnadPerStk: "Cost each",
    frisk: "Healthy",
    nokler: "Keys and quotas",
    nokkel: "Key",
    brukt: "Used",
    rotert: "Rotated",
    renholdsregister: "Arbeidstilsynet's cleaning register",
    aldriHentet: "Never fetched",
    hentingFeilet: "The fetch failed.",
    ingenKontaktServer: "Could not reach the server.",
    henter22: "Fetching 22 MB …",
    hentRegisteret: "Fetch the register now",
    inntektPerManed: "revenue per month",
    oppslagskostnad: "lookup cost",
    marginIProsent: "margin in per cent",
    oppslag: "Lookups",
    inntekt: "Revenue",
    kostnad: "Cost",
    margin: "Margin",
    gjaldt: "Concerned",
    begrunnelse: "Reason",
    igang: "Live",
    underOppstart: "Starting up",
    avtale: "Contract",
    kontoOpprettet: "Account created",
    brukereInvitert: "Users invited",
    leverandorerLest: "Suppliers imported",
    forsteKontrollen: "First check",
    framdrift: "Progress",
    starPa: "Stuck at",
    alleBrukere: "All users",
    merkPersonal: "mark who is staff",
    organisasjon: "Organisation",
    rolleHosKunden: "Role at the customer",
    hosOss: "With us",
    kunde: "Customer",
    begynnASkrive: "Start typing the name …",
    eksisterendeKonto: "Existing account",
    behandlet: "Handled",
    angre: "Undo",
    merkBehandlet: "Mark as handled",
  },
  skjermbilde: {
    nyKontroll: "New check",
    loggUt: "Sign out",
    plussNyKontroll: "+ New check",
    leverandorer: "Suppliers",
    overvakninger: "Monitoring",
    historikk: "History",
    leverandorkjede: "Supply chain",
    aktiveLeverandorer: "Bergen kommune · 148 active suppliers",
    kontrollplikt: "Duty to verify, § 5i",
    dokumentert: "136 of 148 suppliers documented · last updated today",
    sokPlassholder: "Search by company name or org. no. ...",
    alle: "All",
    lavRisiko: "Low risk",
    hoyRisiko: "High risk",
    kolSelskap: "COMPANY",
    kolOrgnr: "ORG. NO.",
    kolSist: "LAST CHECKED",
    kolStatus: "STATUS",
    grense5k: "§ 5k limit",
    hovedleverandor: "Main­contractor",
    ledd: "Tier",
    nyDagligLeder: "New managing director registered",
    tredjeLedd: "Third tier added to the chain",
    leverandorkontroll: "Supplier check",
    svar: "Response",
    vedlegg: "Attachment",
    espdEgenerklaering: "ESPD self-declaration",
    skattOgMva: "Tax and VAT",
    lonnViaBank: "Wages paid via bank",
    laerlingekrav: "Apprentice requirement",
    hoystToLedd: "At most two tiers",
    oppfylt: "Met",
    brudd: "Breach",
  },
  brev: {
    levert: "Delivered",
    erklaeringLevert: "The self-declaration has been delivered.",
    bekreftetAv: "Confirmed by",
    apneVedlegg: "Open",
    mottakerEpost: "Recipient's email",
    fristEttersending: "Deadline for submission",
    forespørselen: "The request",
    kanEndres: "can be edited before it is sent",
    apneIEpost: "Open in email",
    lagreEndringene: "Save the changes",
    markerSendt: "Mark as sent",
    mottattAnnet: "Received another way",
    beOmEttersending: "Request submission",
    brevetLagret: "The letter has been saved.",
    brevetTil: "The letter to the supplier",
    navnetBrukes: "The contact's name is used in the greeting. The link in the letter goes to a page where the supplier uploads the declaration and confirms it with name and role.",
    opplastingslenke: "Upload link:",
    sendtDato: "Sent",
    utenMerknad: "No remarks",
    motstrid: "Contradicts the registers",
    ikkeLevert: "Not delivered",
    venterPaSvar: "Awaiting a reply",
    fristenUte: "Past the deadline",
    fristIDag: "due today",
    dagerOver: "days past the deadline",
    dagerIgjen: "days left",
    kravRedegjorelse: "Request for explanation",
    til: "To",
    kravetMaVaere: "The request must be specific about what is to be explained — a general question about the price does not satisfy the duty.",
    leverandorEpost: "The supplier's email",
    fristForSvar: "Deadline for a reply",
    tiVirkedagerFram: "Ten working days ahead is usual.",
    utkast: "Draft",
    lagreUtkastet: "Save the draft",
    brevet: "The letter",
    kopierTeksten: "Copy the text",
    svarFraLeverandoren: "The supplier's reply",
    lagreSvaret: "Save the reply",
    vurdering: "Assessment",
    tilstrekkelig: "Adequately explained",
    utilstrekkelig: "Inadequate — grounds for rejection",
    lagreVurderingen: "Save the assessment",
    vurdert: "Assessed",
    svarIkkeVurdert: "Reply received — not assessed",
    sendtVenter: "Sent, awaiting a reply",
    limInnSvaret: "Paste the reply you received …",
    hvorforHolder: "Why does the explanation hold, or why not?",
  },
  oppstart: {
    opprettOrganisasjonen: "Create your organisation",
    dittNavn: "Your name",
    oppretter: "Creating …",
    opprettOrganisasjon: "Create organisation",
    velgPlan: "Choose a plan",
    kanByttes: "You can switch or cancel at any time.",
    ikkeIDrift: "Not live yet.",
    vanligst: "Most common",
    betalingsdetaljer: "Payment details",
    koblesSenere: "Will be connected to a payment provider later. The fields are disabled.",
    kortnummer: "Card number",
    utloper: "Expires",
    valgt: "Chosen:",
    fortsettUten: "Continue without payment",
    kontaktRelavo: "Contact Relavo",
    kontaktIngress: "Questions about supplier vetting, pricing or privacy? Send us a message.",
    tilForsiden: "Relavo, to the front page",
    takkFattDen: "Thank you — we have it.",
    svarerInnen: "We normally reply within one working day, to the address you gave.",
    organisasjonFelt: "Organisation",
    telefon: "Phone",
    hvaGjelder: "What is it about?",
    meldingFelt: "Message",
  },
  betaling: {
    faktura: "Invoice",
    fakturaTekst: "We run a credit check and open the account the same working day. The invoice is sent as EHF with 30 days to pay.",
    kort: "Card",
    kortTekst: "Paid at Stripe. The account opens as soon as the payment is confirmed.",
    kortAv: "Not connected yet. Choose invoice and we will get in touch.",
    tilBetaling: "Continue to payment",
    bestillFaktura: "Order against invoice",
    stripeNote: "You are sent to Stripe. We never receive your card number.",
    fakturaNote: "No lock-in. You can cancel from the account settings.",
    bareAdministrator: "Only the organisation's administrator can choose a plan and order. Contact whoever created the account.",
    venterKreditt: "Awaiting credit check",
    venterBetaling: "Awaiting payment",
    aktiv: "Active",
    avslatt: "Declined",
    stengt: "Closed",
    godkjennOgApne: "Approve and open the account",
    kreverForskudd: "Require prepayment",
    betalingMottatt: "Payment received — open the account",
    avslaa: "Decline",
    avslagGrunn: "Why is it declined?",
    bestiltDen: "Ordered",
    venterPaOss: "Waiting on us",
    ingenVenter: "No accounts are waiting for approval.",
    nyeBestillinger: "New orders",
    betalingsmate: "Payment method",
    forskudd: "Prepayment",
  },
  registrering: {
    tittel: "Create an account",
    ingress: "Two minutes. You add the company in the next step.",
    opprett: "Create account",
    harKonto: "Already have an account?",
    nyKunde: "New customer?",
    registrerDeg: "Create an account",
  },
  auth: {
    feilInnlogging: "Wrong email or password.",
    microsoftAv: "Microsoft sign-in is not switched on yet. Use email and password for now.",
    microsoftFeil: "Could not reach Microsoft. Try again.",
    senderTilMicrosoft: "Sending you to Microsoft …",
    engangskodeTittel: "One-time code",
    kodenStemmerIkke: "That code is not right. Try the one showing now.",
    fortsett: "Continue",
    feilPassord: "Wrong password.",
    slippMegInn: "Let me in",
    underUtvikling: "The site is under development and not open yet.",
    loggInn: "Sign in",
    undertittel: "Supplier vetting for public procurement",
    epost: "Email",
    passord: "Password",
    eller: "or",
    medMicrosoft: "Sign in with Microsoft",
    kommer: "coming",
    loggerInn: "Signing in …",
    tofaktor: "Two-factor",
    engangskode: "Enter the code your app shows",
    bekreft: "Confirm",
    bekrefter: "Confirming …",
  },
};
